import { getDestinationFallbackImage } from './fallbackImages'

export const DESTINATION_GUIDES = [
  {
    slug: 'uk',
    name: 'United Kingdom',
    label: 'GB',
    tagline: 'Prestige, career pathways, and broad scholarship visibility.',
    overview:
      'The UK remains one of the strongest destinations for students who want globally recognized degrees, shorter study timelines, and access to leading research and professional networks.',
    theme: {
      start: '#081a39',
      mid: '#133a6b',
      end: '#5b1f3c',
      accent: '#f3c95d',
      accentSoft: 'rgba(243, 201, 93, 0.16)',
      glow: 'rgba(243, 201, 93, 0.26)',
      overlayStart: 'rgba(8, 26, 57, 0.78)',
      overlayEnd: 'rgba(19, 58, 107, 0.42)',
    },
    spotlight: {
      kicker: 'Featured funding lane',
      title: 'Chevening and Commonwealth keep UK funding highly visible',
      body:
        'Students targeting leadership, policy, public service, or taught postgraduate routes usually start here before layering in university merit awards.',
      tags: ['Chevening', 'Commonwealth', '1-year masters'],
    },
    bestFit: [
      'Students who want shorter masters programs',
      'Applicants chasing global prestige and employer visibility',
      'Students balancing scholarships with strong post-study work plans',
    ],
    quickFacts: {
      tuition: 'GBP 11,000 - 28,000 per year',
      living: 'GBP 900 - 1,700 per month',
      work: 'Up to 20 hours per week during term',
      postStudy: 'Strong post-study work pathways for eligible graduates',
      intakes: 'Mainly January and September',
    },
    universities: ['University of Manchester', 'University of Leeds', 'Coventry University', 'University of Birmingham'],
    scholarships: ['Chevening Scholarships', 'Commonwealth Scholarships', 'GREAT Scholarships', 'University-specific merit awards'],
    fellowships: ['Research council funding routes', 'Graduate research assistantships', 'Selected doctoral fellowships'],
    popularFields: ['Business and Finance', 'Engineering', 'Computer Science', 'Law', 'Public Health'],
    whyChoose: [
      "Shorter master's programs compared with many destinations",
      'High concentration of top-ranked universities',
      'Strong international student communities',
      'Clear employability value in global markets',
    ],
    admissions: [
      'Academic transcripts and certificates',
      'Personal statement',
      'English proficiency results where required',
      'Financial documents for visa and tuition planning',
    ],
    studentLife: ['London, Manchester, Leeds, Birmingham', 'Diverse campus life', 'Part-time work access', 'Strong alumni networks'],
  },
  {
    slug: 'australia',
    name: 'Australia',
    label: 'AU',
    tagline: 'High-quality teaching, research, and student support.',
    overview:
      'Australia is a strong option for students who want internationally respected universities, attractive student cities, and good academic support systems.',
    theme: {
      start: '#072b36',
      mid: '#0d5f6d',
      end: '#1d8a78',
      accent: '#ffd166',
      accentSoft: 'rgba(255, 209, 102, 0.18)',
      glow: 'rgba(255, 209, 102, 0.22)',
      overlayStart: 'rgba(7, 43, 54, 0.76)',
      overlayEnd: 'rgba(13, 95, 109, 0.4)',
    },
    spotlight: {
      kicker: 'Featured funding lane',
      title: 'Merit awards and research training make Australia flexible',
      body:
        'Australia works well for students comparing teaching quality, post-study outcomes, and university-specific funding rather than relying on one single flagship award.',
      tags: ['Merit aid', 'Research training', 'Student cities'],
    },
    bestFit: [
      'Students who want strong campus support systems',
      'Applicants comparing employability with lifestyle quality',
      'Research-focused students looking at PhD stipends and labs',
    ],
    quickFacts: {
      tuition: 'AUD 20,000 - 45,000 per year',
      living: 'AUD 1,500 - 2,800 per month',
      work: 'Work rights available under student visa rules',
      postStudy: 'Good graduate work and residency interest for many students',
      intakes: 'February, July, and selected rolling intakes',
    },
    universities: ['Deakin University', 'Griffith University', 'University of Adelaide', 'Monash University'],
    scholarships: ['Destination Australia awards', 'University merit scholarships', 'Faculty-based bursaries', 'Research training scholarships'],
    fellowships: ['Graduate research scholarships', 'PhD stipend routes', 'University research fellowships'],
    popularFields: ['Health Sciences', 'Engineering', 'Data and IT', 'Business', 'Education'],
    whyChoose: [
      'Globally recognized universities',
      'Strong support for international students',
      'Excellent lifestyle and student cities',
      'Practical career-focused programs',
    ],
    admissions: [
      'Academic records and passport details',
      'English test scores where required',
      'Statement or personal profile for some programs',
      'Financial preparation for tuition and visa evidence',
    ],
    studentLife: ['Melbourne, Sydney, Brisbane, Adelaide', 'Multicultural campuses', 'Research strength', 'Active student services'],
  },
  {
    slug: 'canada',
    name: 'Canada',
    label: 'CA',
    tagline: 'Excellent employability, welcoming campuses, and strong graduate opportunities.',
    overview:
      'Canada is consistently popular for students looking for respected education, welcoming communities, and strong long-term career interest after graduation.',
    theme: {
      start: '#0b203f',
      mid: '#144c71',
      end: '#2d6a4f',
      accent: '#f2b84b',
      accentSoft: 'rgba(242, 184, 75, 0.16)',
      glow: 'rgba(242, 184, 75, 0.24)',
      overlayStart: 'rgba(11, 32, 63, 0.78)',
      overlayEnd: 'rgba(20, 76, 113, 0.4)',
    },
    spotlight: {
      kicker: 'Featured funding lane',
      title: 'Canada stands out when scholarships and long-term planning meet',
      body:
        'Students often combine major named awards like Lester B. Pearson or Vanier with entrance scholarships, graduate assistantships, and institution-led funding.',
      tags: ['Pearson', 'Vanier', 'Entrance awards'],
    },
    bestFit: [
      'Students planning both study and employability pathways',
      'Applicants who want strong public universities plus college options',
      'Graduate students looking for assistantships and research funding',
    ],
    quickFacts: {
      tuition: 'CAD 15,000 - 35,000 per year',
      living: 'CAD 1,200 - 2,400 per month',
      work: 'Work rights available for many students while studying',
      postStudy: 'Popular destination for post-study work and migration planning',
      intakes: 'January, May, and September',
    },
    universities: ['University of Windsor', 'York University', 'University of Manitoba', 'University of British Columbia'],
    scholarships: [
      'Global Affairs Canada scholarships',
      'University of Toronto Lester B. Pearson Scholarship',
      'University of British Columbia International Scholars Program',
      'McGill University entrance awards',
    ],
    fellowships: ['Vanier Canada Graduate Scholarships', 'Graduate assistantships', 'Provincial and institutional research funding'],
    popularFields: ['Engineering', 'Business', 'Computer Science', 'Public Policy', 'Health'],
    whyChoose: [
      'High student satisfaction and support systems',
      'Flexible academic pathways across universities and colleges',
      'Strong employability interest from international students',
      'Wide scholarship visibility at major institutions',
    ],
    admissions: [
      'Academic transcripts and completion documents',
      'Language test scores where needed',
      'Program-specific essays or references for competitive schools',
      'Financial planning documents',
    ],
    studentLife: ['Toronto, Vancouver, Winnipeg, Montreal', 'Safe communities', 'Research-friendly environment', 'Large international student base'],
  },
  {
    slug: 'usa',
    name: 'United States',
    label: 'US',
    tagline: 'Massive university choice, research power, and scholarship range.',
    overview:
      'The U.S. offers one of the broadest higher education systems in the world, making it a strong destination for students who want choice, research depth, and diverse campus experiences.',
    theme: {
      start: '#101934',
      mid: '#1f4d8a',
      end: '#8d1f3f',
      accent: '#f2c14f',
      accentSoft: 'rgba(242, 193, 79, 0.16)',
      glow: 'rgba(242, 193, 79, 0.24)',
      overlayStart: 'rgba(16, 25, 52, 0.8)',
      overlayEnd: 'rgba(31, 77, 138, 0.42)',
    },
    spotlight: {
      kicker: 'Featured funding lane',
      title: 'The U.S. has the broadest spread of merit, need-based, and research aid',
      body:
        'Students can mix institutional aid, honors scholarships, fellowships, assistantships, and NCAA opportunities depending on program level and school type.',
      tags: ['Fulbright', 'Need-based aid', 'NCAA options'],
    },
    bestFit: [
      'Students who want the widest possible course choice',
      'Applicants chasing research output, labs, and graduate funding',
      'Students who value campus life, sports, and internship ecosystems',
    ],
    quickFacts: {
      tuition: 'USD 18,000 - 55,000 per year',
      living: 'USD 1,200 - 3,000 per month',
      work: 'Limited on-campus and authorized practical options under student visa rules',
      postStudy: 'Strong pathways through internships, OPT, and graduate research routes',
      intakes: 'August, January, and selected spring/summer starts',
    },
    universities: ['Arizona State University', 'Pace University', 'University of South Florida', 'Northeastern University'],
    scholarships: ['Fulbright Program', 'University merit scholarships', 'Need-based institutional aid', 'Departmental awards'],
    fellowships: ['Graduate assistantships', 'Research fellowships', 'Teaching fellowships', 'STEM funding pathways'],
    popularFields: ['Computer Science', 'Engineering', 'Business', 'Film and Media', 'Biological Sciences'],
    whyChoose: [
      'Huge range of majors and minors',
      'Top global research universities',
      'Strong sports, campus life, and internship culture',
      'Competitive scholarships at many private and public institutions',
    ],
    admissions: [
      'Transcripts and school reports',
      'Essays or personal statements for many universities',
      'English test scores where required',
      'Financial and visa preparation documents',
    ],
    studentLife: ['Boston, New York, Florida, California, Texas', 'Dynamic campus culture', 'Strong alumni networks', 'Large employer ecosystems'],
  },
  {
    slug: 'new-zealand',
    name: 'New Zealand',
    label: 'NZ',
    tagline: 'Supportive study culture with strong quality standards.',
    overview:
      'New Zealand is a student-friendly destination known for quality assurance, a calm study environment, and well-supported academic systems.',
    theme: {
      start: '#06283d',
      mid: '#0f5c7a',
      end: '#1f7a8c',
      accent: '#ffd166',
      accentSoft: 'rgba(255, 209, 102, 0.16)',
      glow: 'rgba(255, 209, 102, 0.22)',
      overlayStart: 'rgba(6, 40, 61, 0.78)',
      overlayEnd: 'rgba(15, 92, 122, 0.4)',
    },
    spotlight: {
      kicker: 'Featured funding lane',
      title: 'New Zealand is strongest when students want quality and calm over crowding',
      body:
        'Funding is usually more university-led, with postgraduate research support becoming especially important for masters and doctoral applicants.',
      tags: ['Quality assurance', 'Research support', 'Lifestyle value'],
    },
    bestFit: [
      'Students who prefer a smaller and more supportive study environment',
      'Applicants in agriculture, sustainability, health, or applied business',
      'Students prioritizing wellbeing alongside degree quality',
    ],
    quickFacts: {
      tuition: 'NZD 20,000 - 38,000 per year',
      living: 'NZD 1,300 - 2,300 per month',
      work: 'Student work rights available under visa rules',
      postStudy: 'Strong appeal for students seeking quality of life plus career development',
      intakes: 'February and July primarily',
    },
    universities: ['University of Auckland', 'Massey University', 'AUT', 'University of Otago'],
    scholarships: ['University international scholarships', 'Government-linked awards', 'Postgraduate research support', 'Faculty scholarships'],
    fellowships: ['Doctoral scholarships', 'Research stipends', 'Graduate research awards'],
    popularFields: ['Agriculture', 'Environmental Science', 'Business', 'IT', 'Health Sciences'],
    whyChoose: [
      'Supportive student environment',
      'High academic quality assurance',
      'Strong reputation in sustainability and applied disciplines',
      'Appealing lifestyle and safety profile',
    ],
    admissions: [
      'Academic records',
      'English proficiency results where applicable',
      'Program-specific supporting documents',
      'Budget and visa planning materials',
    ],
    studentLife: ['Auckland, Wellington, Christchurch, Dunedin', 'Balanced lifestyle', 'Research-friendly campuses', 'Smaller class environments'],
  },
  {
    slug: 'dubai',
    name: 'Dubai',
    label: 'AE',
    tagline: 'Modern branch campuses and strong regional access.',
    overview:
      'Dubai offers international branch campuses, practical business exposure, and a cosmopolitan student experience in a fast-moving global city.',
    theme: {
      start: '#132236',
      mid: '#20506f',
      end: '#8a6130',
      accent: '#ffd27d',
      accentSoft: 'rgba(255, 210, 125, 0.18)',
      glow: 'rgba(255, 210, 125, 0.24)',
      overlayStart: 'rgba(19, 34, 54, 0.78)',
      overlayEnd: 'rgba(32, 80, 111, 0.4)',
    },
    spotlight: {
      kicker: 'Featured funding lane',
      title: 'Dubai shines through branch-campus discounts and business-facing study',
      body:
        'This route is strong for students who want international degree brands, city access, and faster decision timelines through institution-specific scholarships.',
      tags: ['Branch campuses', 'Merit discounts', 'Regional hub'],
    },
    bestFit: [
      'Students who want an international campus inside a global city',
      'Applicants looking for business, media, or architecture pathways',
      'Students who value location, connectivity, and modern infrastructure',
    ],
    quickFacts: {
      tuition: 'AED 35,000 - 80,000 per year',
      living: 'AED 3,500 - 7,500 per month',
      work: 'Varies by visa and institutional setup',
      postStudy: 'Strong appeal for students interested in regional business hubs',
      intakes: 'September, January, and selected summer starts',
    },
    universities: ['University of Birmingham Dubai', 'Middlesex Dubai', 'Heriot-Watt Dubai', 'Murdoch University Dubai'],
    scholarships: ['Branch campus merit scholarships', 'Academic excellence discounts', 'Early payment and regional awards', 'Program-specific tuition reductions'],
    fellowships: ['Selected postgraduate research pathways', 'Industry-linked applied research opportunities'],
    popularFields: ['Business', 'Architecture', 'Computer Science', 'Hospitality', 'Media'],
    whyChoose: [
      'International campus brands in one city',
      'Excellent regional connectivity',
      'Modern infrastructure and business exposure',
      'Good fit for career-focused students',
    ],
    admissions: [
      'Academic transcripts',
      'Passport and identity documents',
      'English test results where required',
      'Financial readiness for tuition and living costs',
    ],
    studentLife: ['Dubai Knowledge Park and academic zones', 'Highly international student body', 'Modern city life', 'Good internship exposure'],
  },
  {
    slug: 'europe',
    name: 'Europe',
    label: 'EU',
    tagline: 'Affordable pathways, cultural range, and expanding English-taught options.',
    overview:
      'Europe offers a wide mix of affordable universities, English-taught programs, and strong mobility opportunities across multiple countries.',
    theme: {
      start: '#0c2340',
      mid: '#355c7d',
      end: '#5e8b7e',
      accent: '#f4c66b',
      accentSoft: 'rgba(244, 198, 107, 0.18)',
      glow: 'rgba(244, 198, 107, 0.22)',
      overlayStart: 'rgba(12, 35, 64, 0.78)',
      overlayEnd: 'rgba(53, 92, 125, 0.42)',
    },
    spotlight: {
      kicker: 'Featured funding lane',
      title: 'Europe is strongest when affordability and mobility matter together',
      body:
        'Students often compare Erasmus+, country-led tuition advantages, and English-taught programs across several cities before choosing the best value.',
      tags: ['Erasmus+', 'Lower tuition', 'Multi-country options'],
    },
    bestFit: [
      'Students comparing cost against global degree quality',
      'Applicants open to different countries, not just one city',
      'Students who want multilingual and multicultural exposure',
    ],
    quickFacts: {
      tuition: 'EUR 3,000 - 20,000 per year depending on country',
      living: 'EUR 700 - 1,800 per month',
      work: 'Varies by country and visa policy',
      postStudy: 'Wide range of graduate routes depending on the country chosen',
      intakes: 'Mostly September, with selected February starts',
    },
    universities: ['EU Business School', 'University of Europe', 'Budapest Metropolitan University', 'Constructor University'],
    scholarships: ['Erasmus+ in Europe', 'DAAD in Germany', 'University-specific merit awards', 'Regional tuition grants'],
    fellowships: ['Graduate research funding', 'Doctoral stipends in selected countries', 'Mobility fellowships'],
    popularFields: ['Business', 'International Relations', 'Engineering', 'Data Science', 'Design'],
    whyChoose: [
      'Potentially lower tuition in many countries',
      'Strong access to multilingual and multicultural environments',
      'Growing number of English-taught programs',
      'Strong value for students comparing cost and quality',
    ],
    admissions: [
      'Country-specific academic requirements',
      'English or local-language requirements depending on program',
      'Motivation letters for many competitive schools',
      'Visa and budget planning based on chosen country',
    ],
    studentLife: ['Germany, Netherlands, Hungary, France, Spain and more', 'Cross-border travel opportunities', 'Varied living costs', 'Strong cultural exposure'],
  },
  {
    slug: 'malaysia',
    name: 'Malaysia',
    label: 'MY',
    tagline: 'Cost-effective international study with good urban campus life.',
    overview:
      'Malaysia is a strong value destination for students who want lower overall cost, international programs, and a diverse multicultural environment.',
    theme: {
      start: '#0f213d',
      mid: '#155263',
      end: '#1f7a6d',
      accent: '#f9c74f',
      accentSoft: 'rgba(249, 199, 79, 0.16)',
      glow: 'rgba(249, 199, 79, 0.22)',
      overlayStart: 'rgba(15, 33, 61, 0.78)',
      overlayEnd: 'rgba(21, 82, 99, 0.42)',
    },
    spotlight: {
      kicker: 'Featured funding lane',
      title: 'Malaysia works best when budget and international exposure must stay balanced',
      body:
        'Students usually rely on university merit support, transfer-friendly pathways, and comparatively lower living costs to keep the full study plan manageable.',
      tags: ['Value destination', 'Branch campuses', 'Lower living cost'],
    },
    bestFit: [
      'Students who want affordable study without giving up international options',
      'Applicants comparing medicine, hospitality, computing, and business',
      'Families who want lower living costs and clear budget planning',
    ],
    quickFacts: {
      tuition: 'USD 4,000 - 12,000 per year',
      living: 'USD 400 - 900 per month',
      work: 'Limited part-time work options under visa rules',
      postStudy: 'Good option for affordable degree planning and regional mobility',
      intakes: 'Multiple intakes across the year depending on institution',
    },
    universities: ["Taylor's University", 'Sunway University', 'UCSI University', 'Monash University Malaysia'],
    scholarships: ['University merit scholarships', 'International student discounts', 'Faculty awards', 'Selected partner scholarships'],
    fellowships: ['Postgraduate research support', 'Graduate stipends in selected universities'],
    popularFields: ['Medicine', 'Hospitality', 'Engineering', 'Business', 'Computing'],
    whyChoose: [
      'Lower living and tuition costs than many major destinations',
      'International branch campuses available',
      'Good fit for budget-conscious students',
      'Strong campus diversity and urban convenience',
    ],
    admissions: [
      'Academic transcripts and certificates',
      'Passport documentation',
      'Language readiness where required',
      'Visa and tuition planning documents',
    ],
    studentLife: ['Kuala Lumpur and other major student cities', 'Affordable transport and housing', 'Multicultural environment', 'Accessible regional travel'],
  },
  {
    slug: 'turkey',
    name: 'Turkey',
    label: 'TR',
    tagline: 'Affordable tuition, cultural depth, and rising scholarship access.',
    overview:
      'Turkey offers competitive tuition, a rich cross-cultural environment, and growing international student pathways in both public and private institutions.',
    theme: {
      start: '#1c1c3a',
      mid: '#8c3b2f',
      end: '#c38b3d',
      accent: '#ffd166',
      accentSoft: 'rgba(255, 209, 102, 0.18)',
      glow: 'rgba(255, 209, 102, 0.22)',
      overlayStart: 'rgba(28, 28, 58, 0.8)',
      overlayEnd: 'rgba(140, 59, 47, 0.4)',
    },
    spotlight: {
      kicker: 'Featured funding lane',
      title: 'Turkey combines lower tuition with visible government scholarship pathways',
      body:
        'This destination is often attractive for students comparing affordability, city life, and scholarship-supported entry into medicine, engineering, or business.',
      tags: ['Turkiye Scholarships', 'City campuses', 'Cost advantage'],
    },
    bestFit: [
      'Students comparing tuition value against major-city living',
      'Applicants interested in engineering, health, or architecture',
      'Students who want scholarship possibilities alongside a lower-cost plan',
    ],
    quickFacts: {
      tuition: 'USD 3,000 - 15,000 per year',
      living: 'USD 400 - 1,000 per month',
      work: 'Varies by program level and visa rules',
      postStudy: 'Good option for students comparing affordability and international exposure',
      intakes: 'Mostly September and selected winter intakes',
    },
    universities: ['Bahcesehir University', 'Istanbul Aydin University', 'Ozyegin University', 'Istanbul Medipol University'],
    scholarships: ['Turkiye Scholarships', 'University merit awards', 'International tuition discounts', 'Program-level academic scholarships'],
    fellowships: ['Selected graduate research routes', 'Academic project funding in some institutions'],
    popularFields: ['Engineering', 'Medicine', 'Architecture', 'Business', 'International Trade'],
    whyChoose: [
      'Affordable tuition compared with many Western destinations',
      'Strong blend of European and Asian cultural exposure',
      'Rising scholarship interest for international students',
      'Good fit for students seeking value and city life',
    ],
    admissions: [
      'Academic transcripts',
      'Passport documentation',
      'Language readiness depending on program medium',
      'Budget and visa support paperwork',
    ],
    studentLife: ['Istanbul, Ankara, Izmir', 'Large urban student communities', 'Lower cost options', 'Cultural richness and travel access'],
  },
  {
    slug: 'china',
    name: 'China',
    label: 'CN',
    tagline: 'Strong research scale, technology exposure, and growing scholarship access.',
    overview:
      'China is increasingly attractive for students looking for large research universities, engineering and technology strength, and a broad mix of scholarship-supported study paths.',
    theme: {
      start: '#1a1b2f',
      mid: '#5a2530',
      end: '#b0442a',
      accent: '#f7c55f',
      accentSoft: 'rgba(247, 197, 95, 0.16)',
      glow: 'rgba(247, 197, 95, 0.24)',
      overlayStart: 'rgba(26, 27, 47, 0.8)',
      overlayEnd: 'rgba(90, 37, 48, 0.42)',
    },
    spotlight: {
      kicker: 'Featured funding lane',
      title: 'China is strongest for technology-driven study with scholarship upside',
      body:
        'Students often compare Chinese Government Scholarships, provincial funding, and elite university research environments when planning AI, engineering, business, or trade pathways.',
      tags: ['Government scholarships', 'AI and engineering', 'Large research universities'],
    },
    bestFit: [
      'Students targeting AI, engineering, manufacturing, or global trade',
      'Applicants who want strong research ecosystems at a lower cost than many Western options',
      'Students open to fast-growing cities and innovation-heavy campuses',
    ],
    quickFacts: {
      tuition: 'USD 3,500 - 12,000 per year',
      living: 'USD 450 - 1,200 per month',
      work: 'Varies by city, university, and visa permissions',
      postStudy: 'Growing interest for students in technology, business, and global trade pathways',
      intakes: 'Mostly September, with selected spring starts',
    },
    universities: ['Tsinghua University', 'Peking University', 'Fudan University', 'Shanghai Jiao Tong University'],
    scholarships: ['Chinese Government Scholarship', 'University scholarships', 'Provincial scholarships', 'Bilateral program funding'],
    fellowships: ['Graduate research funding', 'Lab-based postgraduate stipends', 'University research fellowships'],
    popularFields: ['Engineering', 'Artificial Intelligence', 'Business', 'Medicine', 'International Trade'],
    whyChoose: [
      'Strong technology and research ecosystem',
      'Large number of internationally recognized universities',
      'Good value compared with many Western destinations',
      'Increasing availability of scholarship-supported programs',
    ],
    admissions: [
      'Academic transcripts and certificates',
      'Passport and identity documents',
      'Program language readiness depending on course delivery',
      'Financial and visa preparation materials',
    ],
    studentLife: ['Beijing, Shanghai, Hangzhou, Nanjing', 'Large urban student environments', 'Fast-growing innovation culture', 'Wide transport connectivity'],
  },
]

const DESTINATION_CARD_DEFAULTS = DESTINATION_GUIDES.map((guide) => ({
  slug: guide.slug,
  code: guide.label,
  name: guide.name,
  subtitle: `${Math.max((guide.universities?.length ?? 4) * 15, 15)}+ partner universities`,
  summary: guide.tagline,
  universities: guide.universities ?? [],
  image_url: getDestinationFallbackImage(guide.slug),
}))

const DESTINATION_UNIVERSITY_COLLECTIONS = {
  uk: [
    { name: 'University of Manchester', city: 'Manchester', focus: 'Engineering, business, and research depth' },
    { name: 'University of Leeds', city: 'Leeds', focus: 'Business, law, media, and engineering' },
    { name: 'Coventry University', city: 'Coventry', focus: 'Career-focused programs and practical learning' },
    { name: 'University of Birmingham', city: 'Birmingham', focus: 'Russell Group academics and broad postgraduate options' },
    { name: 'University of Sheffield', city: 'Sheffield', focus: 'Engineering, architecture, and social sciences' },
    { name: 'University of Nottingham', city: 'Nottingham', focus: 'Business, pharmacy, and international relations' },
    { name: 'Queen Mary University of London', city: 'London', focus: 'Law, medicine, and research-led teaching' },
    { name: 'University of Leicester', city: 'Leicester', focus: 'Science, health, and business pathways' },
    { name: 'University of Essex', city: 'Colchester', focus: 'Social sciences, data, and international studies' },
    { name: 'University of Portsmouth', city: 'Portsmouth', focus: 'Computing, logistics, and engineering' },
    { name: 'Brunel University London', city: 'London', focus: 'Design, engineering, and business innovation' },
  ],
  australia: [
    { name: 'Deakin University', city: 'Melbourne', focus: 'Health, IT, education, and business' },
    { name: 'Griffith University', city: 'Brisbane', focus: 'Public health, hospitality, and design' },
    { name: 'University of Adelaide', city: 'Adelaide', focus: 'Engineering, agriculture, and medicine' },
    { name: 'Monash University', city: 'Melbourne', focus: 'Global research and broad postgraduate pathways' },
    { name: 'University of Queensland', city: 'Brisbane', focus: 'Science, medicine, and engineering' },
    { name: 'RMIT University', city: 'Melbourne', focus: 'Design, technology, and applied business' },
    { name: 'Western Sydney University', city: 'Sydney', focus: 'Health, social sciences, and business' },
    { name: 'Macquarie University', city: 'Sydney', focus: 'Finance, data, linguistics, and media' },
    { name: 'La Trobe University', city: 'Melbourne', focus: 'Health, education, and technology' },
    { name: 'University of Technology Sydney', city: 'Sydney', focus: 'Innovation, engineering, and communication' },
    { name: 'Curtin University', city: 'Perth', focus: 'Mining, engineering, and commerce' },
  ],
  canada: [
    { name: 'University of Windsor', city: 'Windsor', focus: 'Engineering, business, and professional programs' },
    { name: 'York University', city: 'Toronto', focus: 'Business, law, media, and policy' },
    { name: 'University of Manitoba', city: 'Winnipeg', focus: 'Agriculture, engineering, and science' },
    { name: 'University of British Columbia', city: 'Vancouver', focus: 'Prestige academics and research' },
    { name: 'University of Toronto', city: 'Toronto', focus: 'Top-tier global research and wide scholarship visibility' },
    { name: 'McGill University', city: 'Montreal', focus: 'Medicine, business, and advanced research' },
    { name: 'University of Alberta', city: 'Edmonton', focus: 'Energy, engineering, and life sciences' },
    { name: 'Simon Fraser University', city: 'Burnaby', focus: 'Computing, communication, and policy' },
    { name: 'Carleton University', city: 'Ottawa', focus: 'Public affairs, engineering, and journalism' },
    { name: 'Toronto Metropolitan University', city: 'Toronto', focus: 'Applied business, design, and technology' },
    { name: 'Memorial University of Newfoundland', city: "St. John's", focus: 'Value-driven study and engineering' },
  ],
  usa: [
    { name: 'Arizona State University', city: 'Phoenix', focus: 'Innovation, engineering, and business' },
    { name: 'Pace University', city: 'New York', focus: 'Business, finance, and urban professional study' },
    { name: 'University of South Florida', city: 'Tampa', focus: 'Research growth and value-oriented public education' },
    { name: 'Northeastern University', city: 'Boston', focus: 'Co-op learning and industry-linked degrees' },
    { name: 'University of Illinois Chicago', city: 'Chicago', focus: 'Health, engineering, and urban research' },
    { name: 'Michigan State University', city: 'East Lansing', focus: 'Business, agriculture, and communication' },
    { name: 'University of Arizona', city: 'Tucson', focus: 'Science, optics, and business' },
    { name: 'Drexel University', city: 'Philadelphia', focus: 'Co-op education and applied engineering' },
    { name: 'George Mason University', city: 'Virginia', focus: 'Policy, computing, and economics' },
    { name: 'Saint Louis University', city: 'St. Louis', focus: 'Health sciences, aviation, and business' },
    { name: 'University of Dayton', city: 'Dayton', focus: 'Engineering, entrepreneurship, and student support' },
  ],
  'new-zealand': [
    { name: 'University of Auckland', city: 'Auckland', focus: 'Top-ranked academics and broad research' },
    { name: 'Massey University', city: 'Palmerston North', focus: 'Agriculture, aviation, and design' },
    { name: 'AUT', city: 'Auckland', focus: 'Industry-facing modern education' },
    { name: 'University of Otago', city: 'Dunedin', focus: 'Medicine, law, and sciences' },
    { name: 'Victoria University of Wellington', city: 'Wellington', focus: 'Policy, law, and humanities' },
    { name: 'University of Canterbury', city: 'Christchurch', focus: 'Engineering and environmental sciences' },
    { name: 'Lincoln University', city: 'Lincoln', focus: 'Agriculture, land, and sustainability' },
    { name: 'Waikato University', city: 'Hamilton', focus: 'Business, computing, and education' },
    { name: 'Eastern Institute of Technology', city: 'Napier', focus: 'Applied learning and vocational pathways' },
    { name: 'Unitec Institute of Technology', city: 'Auckland', focus: 'Built environment and practical training' },
    { name: 'Otago Polytechnic', city: 'Dunedin', focus: 'Applied design, nursing, and business' },
  ],
  dubai: [
    { name: 'University of Birmingham Dubai', city: 'Dubai', focus: 'UK degree pathway and broad academics' },
    { name: 'Middlesex Dubai', city: 'Dubai', focus: 'Business, media, law, and computing' },
    { name: 'Heriot-Watt Dubai', city: 'Dubai', focus: 'Engineering, construction, and business' },
    { name: 'Murdoch University Dubai', city: 'Dubai', focus: 'Australian-linked business and tech programs' },
    { name: 'Canadian University Dubai', city: 'Dubai', focus: 'Business, architecture, and communication' },
    { name: 'University of Wollongong in Dubai', city: 'Dubai', focus: 'Business, IT, and engineering' },
    { name: 'Manipal Academy of Higher Education Dubai', city: 'Dubai', focus: 'Engineering, media, and management' },
    { name: 'Amity University Dubai', city: 'Dubai', focus: 'Business, IT, and applied sciences' },
    { name: 'Curtin University Dubai', city: 'Dubai', focus: 'Business, commerce, and technology' },
    { name: 'SP Jain School of Global Management', city: 'Dubai', focus: 'Business and global leadership' },
    { name: 'Rochester Institute of Technology Dubai', city: 'Dubai', focus: 'Computing, engineering, and analytics' },
  ],
  europe: [
    { name: 'EU Business School', city: 'Barcelona', focus: 'International business and management' },
    { name: 'University of Europe', city: 'Germany', focus: 'Applied business, design, and software' },
    { name: 'Budapest Metropolitan University', city: 'Budapest', focus: 'Affordable English-taught degrees' },
    { name: 'Constructor University', city: 'Bremen', focus: 'STEM and international learning' },
    { name: 'University of Debrecen', city: 'Hungary', focus: 'Medicine, science, and business' },
    { name: 'Fontys University of Applied Sciences', city: 'Netherlands', focus: 'Applied technology and business' },
    { name: 'Vistula University', city: 'Warsaw', focus: 'Business, tourism, and computing' },
    { name: 'GISMA University of Applied Sciences', city: 'Germany', focus: 'Business, analytics, and tech' },
    { name: 'University of Padua', city: 'Italy', focus: 'Research, medicine, and engineering' },
    { name: 'Kozminski University', city: 'Poland', focus: 'Business and management excellence' },
    { name: 'Czech University of Life Sciences Prague', city: 'Prague', focus: 'Agriculture, economics, and sustainability' },
  ],
  malaysia: [
    { name: "Taylor's University", city: 'Kuala Lumpur', focus: 'Hospitality, medicine, and business' },
    { name: 'Sunway University', city: 'Kuala Lumpur', focus: 'Business, communication, and IT' },
    { name: 'UCSI University', city: 'Kuala Lumpur', focus: 'Medicine, engineering, and music' },
    { name: 'Monash University Malaysia', city: 'Kuala Lumpur', focus: 'Australian-linked degree pathway' },
    { name: 'University of Malaya', city: 'Kuala Lumpur', focus: 'Prestige public university research' },
    { name: 'Asia Pacific University', city: 'Kuala Lumpur', focus: 'Technology, cyber security, and business' },
    { name: 'INTI International University', city: 'Nilai', focus: 'Transfers, business, and engineering' },
    { name: 'HELP University', city: 'Kuala Lumpur', focus: 'Psychology, law, and business' },
    { name: 'Multimedia University', city: 'Cyberjaya', focus: 'Computing, engineering, and digital media' },
    { name: 'SEGi University', city: 'Kota Damansara', focus: 'Health, business, and built environment' },
    { name: 'UOW Malaysia', city: 'Penang', focus: 'Hospitality, business, and technology' },
  ],
  turkey: [
    { name: 'Bahcesehir University', city: 'Istanbul', focus: 'International business, engineering, and architecture' },
    { name: 'Istanbul Aydin University', city: 'Istanbul', focus: 'Engineering, aviation, and business' },
    { name: 'Ozyegin University', city: 'Istanbul', focus: 'Business, engineering, and entrepreneurship' },
    { name: 'Istanbul Medipol University', city: 'Istanbul', focus: 'Medicine, pharmacy, and engineering' },
    { name: 'Yeditepe University', city: 'Istanbul', focus: 'Health, law, and communication' },
    { name: 'Istanbul Bilgi University', city: 'Istanbul', focus: 'Business, design, and media' },
    { name: 'Koc University', city: 'Istanbul', focus: 'Research prestige and strong scholarship visibility' },
    { name: 'Sabanci University', city: 'Istanbul', focus: 'Engineering, business, and interdisciplinary study' },
    { name: 'Ankara University', city: 'Ankara', focus: 'Public university pathways and broad faculties' },
    { name: 'Altinbas University', city: 'Istanbul', focus: 'Business, dentistry, and architecture' },
    { name: 'Hacettepe University', city: 'Ankara', focus: 'Medicine and research excellence' },
  ],
  china: [
    { name: 'Tsinghua University', city: 'Beijing', focus: 'Engineering, AI, and advanced research' },
    { name: 'Peking University', city: 'Beijing', focus: 'Humanities, business, and global prestige' },
    { name: 'Fudan University', city: 'Shanghai', focus: 'Medicine, business, and international studies' },
    { name: 'Shanghai Jiao Tong University', city: 'Shanghai', focus: 'Engineering, computing, and innovation' },
    { name: 'Zhejiang University', city: 'Hangzhou', focus: 'Technology, science, and entrepreneurship' },
    { name: 'Nanjing University', city: 'Nanjing', focus: 'Sciences, arts, and strong research pathways' },
    { name: 'Tongji University', city: 'Shanghai', focus: 'Architecture, civil engineering, and design' },
    { name: 'Huazhong University of Science and Technology', city: 'Wuhan', focus: 'Engineering, medicine, and applied research' },
    { name: 'Beijing Normal University', city: 'Beijing', focus: 'Education, psychology, and social sciences' },
    { name: "Xi'an Jiaotong University", city: "Xi'an", focus: 'Engineering, energy, and manufacturing' },
    { name: 'University of Science and Technology of China', city: 'Hefei', focus: 'Physics, AI, and cutting-edge STEM' },
  ],
}

const DESTINATION_GUIDE_MAP = new Map(DESTINATION_GUIDES.map((guide) => [guide.slug, guide]))

export function mergeDestinationCards(items = []) {
  const existing = Array.isArray(items) ? items : []
  const seen = new Set(existing.map((item) => item.slug))
  const missing = DESTINATION_CARD_DEFAULTS.filter((item) => !seen.has(item.slug))
  return [...existing, ...missing]
}

export function getDestinationGuide(slug) {
  const guide = DESTINATION_GUIDE_MAP.get(slug)
  if (!guide) return null

  return {
    ...guide,
    universityCollection: DESTINATION_UNIVERSITY_COLLECTIONS[slug] ?? [],
  }
}
