export const EVENT_FALLBACKS = [
  {
    id: 'evt-nyc-2026-01',
    title: 'Spring Abroad Planning Night — New York',
    date: '2026-02-21T18:30:00-05:00',
    location: 'Midtown Manhattan, New York',
    description:
      'An in-person planning night for families and students mapping out UK, Canada, Australia, and Europe options for the next intake cycle.',
    image_url: '',
    register_url: '/contact',
    category: 'university_open_day',
    is_online: false,
    is_past: true,
  },
  {
    id: 'evt-online-2026-02',
    title: 'US Parent & Student Scholarship Webinar',
    date: '2026-03-14T19:00:00-04:00',
    location: 'Online',
    description:
      'A focused webinar on merit scholarships, entrance awards, and how to shortlist universities with the strongest funding visibility.',
    image_url: '',
    register_url: '/contact',
    category: 'scholarship',
    is_online: true,
    is_past: true,
  },
  {
    id: 'evt-chicago-2026-03',
    title: 'Midwest Visa & Intake Clinic — Chicago',
    date: '2026-04-09T17:30:00-05:00',
    location: 'Downtown Chicago',
    description:
      'A practical visa and intake clinic covering offer letters, document readiness, and the smartest way to prepare for summer and fall starts.',
    image_url: '',
    register_url: '/contact',
    category: 'visa_talk',
    is_online: false,
    is_past: true,
  },
  {
    id: 'evt-dallas-2026-04',
    title: 'Pre-Departure Bootcamp — Dallas',
    date: '2026-05-10T10:00:00-05:00',
    location: 'Dallas Arts District',
    description:
      'A pre-departure bootcamp for students ready to move from application mode into travel planning, packing, budgeting, and settlement prep.',
    image_url: '',
    register_url: '/contact',
    category: 'pre_departure',
    is_online: false,
    is_past: true,
  },
  {
    id: 'evt-atlanta-2026-05',
    title: 'Atlanta Open Day: UK, Canada & Australia',
    date: '2026-06-12T13:00:00-04:00',
    location: 'Buckhead, Atlanta',
    description:
      'Meet the Brightpath team for one-on-one destination guidance, university shortlisting, and a live review of current admissions pathways.',
    image_url: '',
    register_url: '/contact',
    category: 'university_open_day',
    is_online: false,
    is_past: false,
  },
  {
    id: 'evt-online-2026-06',
    title: 'Visa Masterclass — Build a Strong Study Plan',
    date: '2026-06-26T19:30:00-04:00',
    location: 'Online',
    description:
      'A virtual masterclass on document strategy, visa readiness, funding proof, and how to present a stronger study story to universities.',
    image_url: '',
    register_url: '/contact',
    category: 'visa_talk',
    is_online: true,
    is_past: false,
  },
  {
    id: 'evt-la-2026-07',
    title: 'Scholarship Saturday — West Coast Edition',
    date: '2026-07-18T11:00:00-07:00',
    location: 'Downtown Los Angeles',
    description:
      'An in-person scholarship clinic built for students comparing tuition, merit aid, and postgraduate funding routes across multiple destinations.',
    image_url: '',
    register_url: '/contact',
    category: 'scholarship',
    is_online: false,
    is_past: false,
  },
  {
    id: 'evt-houston-2026-08',
    title: 'Fall Intakes Pre-Departure Mixer — Houston',
    date: '2026-08-08T14:00:00-05:00',
    location: 'Houston Galleria District',
    description:
      'A friendly mixer for students heading out in the fall, with final document checks, packing tips, and a Q&A on settling in abroad.',
    image_url: '',
    register_url: '/contact',
    category: 'pre_departure',
    is_online: false,
    is_past: false,
  },
  {
    id: 'evt-miami-2026-09',
    title: 'Miami International Study Fair',
    date: '2026-09-05T12:00:00-04:00',
    location: 'Brickell, Miami',
    description:
      'A broad study fair featuring destination briefings, application advice, and practical support for students and families exploring multiple countries.',
    image_url: '',
    register_url: '/contact',
    category: 'university_open_day',
    is_online: false,
    is_past: false,
  },
  {
    id: 'evt-online-2026-10',
    title: 'Graduate Study & Funding Week',
    date: '2026-10-17T18:00:00-04:00',
    location: 'Online',
    description:
      'A week-style webinar event covering master’s, PhD, research funding, assistantships, and the best graduate pathways for international students.',
    image_url: '',
    register_url: '/contact',
    category: 'webinar',
    is_online: true,
    is_past: false,
  },
]

export const UPCOMING_EVENT_FALLBACKS = EVENT_FALLBACKS.filter((event) => !event.is_past)
