export const UNIVERSITY_CATALOG = [
  {
    slug: 'university-of-manchester',
    name: 'University of Manchester',
    destination: 'United Kingdom',
    destinationSlug: 'uk',
    city: 'Manchester',
    type: 'Public research university',
    tuition: 'GBP 20,000 - 38,000 per year',
    livingCosts: 'GBP 900 - 1,500 per month',
    overview:
      'A globally recognized UK university known for strong research, broad subject choice, and an active student city environment.',
    programs: ['Engineering', 'Business', 'Computer Science', 'Social Sciences', 'Health Sciences'],
    scholarships: ['Global Futures Scholarships', 'Faculty merit awards', 'Selected postgraduate funding'],
    highlights: ['Research-intensive environment', 'Large international student community', 'Strong city employability links'],
    admissions: ['Strong academic transcripts', 'English proficiency where required', 'Program-specific statements for competitive courses'],
    housing: ['University halls', 'Private student housing', 'Shared city apartments'],
  },
  {
    slug: 'university-of-leeds',
    name: 'University of Leeds',
    destination: 'United Kingdom',
    destinationSlug: 'uk',
    city: 'Leeds',
    type: 'Public research university',
    tuition: 'GBP 19,000 - 34,000 per year',
    livingCosts: 'GBP 850 - 1,400 per month',
    overview:
      'A well-regarded UK institution with strong teaching quality, lively student life, and broad international recruitment.',
    programs: ['Business', 'Law', 'Engineering', 'Media', 'Data Science'],
    scholarships: ['International Excellence Scholarships', 'School-level scholarships', 'Research funding routes'],
    highlights: ['Strong student city reputation', 'Good balance of cost and quality', 'Wide course range'],
    admissions: ['Academic records', 'English test scores if applicable', 'Personal statement for selected programs'],
    housing: ['On-campus residence', 'Private halls', 'Shared housing in Leeds'],
  },
  {
    slug: 'coventry-university',
    name: 'Coventry University',
    destination: 'United Kingdom',
    destinationSlug: 'uk',
    city: 'Coventry',
    type: 'Career-focused public university',
    tuition: 'GBP 16,000 - 27,000 per year',
    livingCosts: 'GBP 800 - 1,250 per month',
    overview:
      'Known for practical learning, employability focus, and accessible study pathways for international students.',
    programs: ['Business', 'Automotive Engineering', 'Computing', 'Design', 'Health'],
    scholarships: ['Vice-Chancellor scholarships', 'International merit discounts', 'Course-based awards'],
    highlights: ['Career-driven curriculum', 'Strong support services', 'Good value compared with larger UK cities'],
    admissions: ['Academic qualifications', 'English requirements', 'Supporting personal documents'],
    housing: ['University accommodation', 'Private student housing', 'Shared apartments'],
  },
  {
    slug: 'university-of-birmingham',
    name: 'University of Birmingham',
    destination: 'United Kingdom',
    destinationSlug: 'uk',
    city: 'Birmingham',
    type: 'Public research university',
    tuition: 'GBP 21,000 - 35,000 per year',
    livingCosts: 'GBP 900 - 1,450 per month',
    overview:
      'A respected Russell Group university with strong academics, global recognition, and a large student population.',
    programs: ['Engineering', 'Medicine', 'Business', 'Public Policy', 'Computer Science'],
    scholarships: ['Global Masters Scholarships', 'Country and partner awards', 'Research funding'],
    highlights: ['Russell Group reputation', 'Major city location', 'Strong postgraduate options'],
    admissions: ['Academic transcript strength', 'English language readiness', 'Program-specific essays for some courses'],
    housing: ['Campus housing', 'City apartments', 'Private student residences'],
  },
  {
    slug: 'deakin-university',
    name: 'Deakin University',
    destination: 'Australia',
    destinationSlug: 'australia',
    city: 'Melbourne',
    type: 'Public university',
    tuition: 'AUD 24,000 - 40,000 per year',
    livingCosts: 'AUD 1,600 - 2,700 per month',
    overview:
      'An Australian university known for flexible learning, practical teaching, and strong student support services.',
    programs: ['Business', 'Health', 'IT', 'Education', 'Engineering'],
    scholarships: ['Vice-Chancellor awards', 'Merit scholarships', 'Regional and faculty-based discounts'],
    highlights: ['Strong student support', 'Modern campuses', 'Good employability focus'],
    admissions: ['Academic transcripts', 'English test evidence where needed', 'Relevant supporting documents'],
    housing: ['On-campus rooms', 'Private rentals', 'Student apartments'],
  },
  {
    slug: 'griffith-university',
    name: 'Griffith University',
    destination: 'Australia',
    destinationSlug: 'australia',
    city: 'Brisbane',
    type: 'Public university',
    tuition: 'AUD 23,000 - 39,000 per year',
    livingCosts: 'AUD 1,500 - 2,500 per month',
    overview:
      'A popular destination for students seeking vibrant campus life, applied programs, and strong support in Queensland.',
    programs: ['Business', 'Hospitality', 'Public Health', 'Engineering', 'Animation and Design'],
    scholarships: ['International student scholarships', 'Academic excellence awards', 'Postgraduate research funding'],
    highlights: ['Strong support culture', 'Good location in Queensland', 'Broad applied course options'],
    admissions: ['Academic history', 'Language test readiness', 'Program-specific documents where required'],
    housing: ['Student residences', 'Shared housing', 'City rentals'],
  },
  {
    slug: 'university-of-adelaide',
    name: 'University of Adelaide',
    destination: 'Australia',
    destinationSlug: 'australia',
    city: 'Adelaide',
    type: 'Public research university',
    tuition: 'AUD 25,000 - 45,000 per year',
    livingCosts: 'AUD 1,400 - 2,300 per month',
    overview:
      'A research-led university offering strong academics, scholarship visibility, and a lower-cost Australian city.',
    programs: ['Engineering', 'Agriculture', 'Business', 'Medicine', 'Data Science'],
    scholarships: ['Global academic excellence awards', 'Faculty scholarships', 'Graduate research support'],
    highlights: ['Strong research reputation', 'Affordable city by Australian standards', 'Good international community'],
    admissions: ['Strong academic records', 'English language evidence', 'Supporting documents for selected programs'],
    housing: ['University housing', 'Private student accommodation', 'Shared rentals'],
  },
  {
    slug: 'monash-university',
    name: 'Monash University',
    destination: 'Australia',
    destinationSlug: 'australia',
    city: 'Melbourne',
    type: 'Public research university',
    tuition: 'AUD 28,000 - 48,000 per year',
    livingCosts: 'AUD 1,700 - 2,800 per month',
    overview:
      'A top Australian university known for scale, research strength, and broad global recognition.',
    programs: ['Pharmacy', 'Business', 'Engineering', 'Computer Science', 'Law'],
    scholarships: ['International merit scholarships', 'Faculty awards', 'Research scholarships'],
    highlights: ['Strong global ranking profile', 'Large campus ecosystem', 'Excellent postgraduate pathways'],
    admissions: ['Competitive academics', 'Language scores', 'Program-specific requirements depending on faculty'],
    housing: ['On-campus accommodation', 'Private rentals', 'Student apartments'],
  },
  {
    slug: 'university-of-windsor',
    name: 'University of Windsor',
    destination: 'Canada',
    destinationSlug: 'canada',
    city: 'Windsor',
    type: 'Public university',
    tuition: 'CAD 18,000 - 31,000 per year',
    livingCosts: 'CAD 1,100 - 1,900 per month',
    overview:
      'A practical Canadian university with a strong student community and access to cross-border economic activity.',
    programs: ['Engineering', 'Business', 'Computer Science', 'Law', 'Social Work'],
    scholarships: ['Entrance scholarships', 'Faculty awards', 'International merit support'],
    highlights: ['Good value in Ontario', 'Supportive campus size', 'Strong professional programs'],
    admissions: ['Academic transcripts', 'English language evidence where required', 'Supporting documents'],
    housing: ['Campus residence', 'Private rentals', 'Shared off-campus housing'],
  },
  {
    slug: 'york-university',
    name: 'York University',
    destination: 'Canada',
    destinationSlug: 'canada',
    city: 'Toronto',
    type: 'Public university',
    tuition: 'CAD 22,000 - 38,000 per year',
    livingCosts: 'CAD 1,500 - 2,500 per month',
    overview:
      'A major Canadian university in Toronto with wide academic choice and strong international student visibility.',
    programs: ['Business', 'Law', 'Media', 'Computer Science', 'Public Policy'],
    scholarships: ['International entrance scholarships', 'Merit awards', 'Program-level support'],
    highlights: ['Toronto access', 'Broad academic range', 'Strong campus diversity'],
    admissions: ['Academic qualifications', 'English readiness', 'Program-specific documents for competitive pathways'],
    housing: ['Campus housing', 'Toronto rentals', 'Private student residences'],
  },
  {
    slug: 'university-of-manitoba',
    name: 'University of Manitoba',
    destination: 'Canada',
    destinationSlug: 'canada',
    city: 'Winnipeg',
    type: 'Public research university',
    tuition: 'CAD 17,000 - 29,000 per year',
    livingCosts: 'CAD 1,100 - 1,800 per month',
    overview:
      'A strong-value Canadian university with good research pathways and relatively manageable cost of living.',
    programs: ['Agriculture', 'Engineering', 'Business', 'Science', 'Architecture'],
    scholarships: ['International student entrance scholarships', 'Research awards', 'Faculty funding'],
    highlights: ['Strong value proposition', 'Research-friendly environment', 'Good graduate study routes'],
    admissions: ['Academic records', 'English test results where required', 'Supporting university documents'],
    housing: ['Residence halls', 'Shared rentals', 'Private housing near campus'],
  },
  {
    slug: 'university-of-british-columbia',
    name: 'University of British Columbia',
    destination: 'Canada',
    destinationSlug: 'canada',
    city: 'Vancouver',
    type: 'Public research university',
    tuition: 'CAD 23,000 - 48,000 per year',
    livingCosts: 'CAD 1,700 - 2,900 per month',
    overview:
      'One of Canada’s best-known universities with strong academics, research intensity, and prestigious scholarship options.',
    programs: ['Forestry', 'Business', 'Engineering', 'Computer Science', 'Public Health'],
    scholarships: ['International Scholars Program', 'Merit awards', 'Faculty and research scholarships'],
    highlights: ['Top global reputation', 'Prestige scholarships', 'Beautiful Vancouver campus setting'],
    admissions: ['Competitive academic profile', 'English language requirements', 'Strong application package'],
    housing: ['Campus residences', 'Private Vancouver rentals', 'Student housing communities'],
  },
  {
    slug: 'arizona-state-university',
    name: 'Arizona State University',
    destination: 'United States',
    destinationSlug: 'usa',
    city: 'Phoenix',
    type: 'Public research university',
    tuition: 'USD 28,000 - 38,000 per year',
    livingCosts: 'USD 1,200 - 2,100 per month',
    overview:
      'A large U.S. university recognized for innovation, strong program breadth, and a very active campus ecosystem.',
    programs: ['Engineering', 'Business', 'Computer Science', 'Journalism', 'Design'],
    scholarships: ['New American University scholarships', 'Department awards', 'International merit support'],
    highlights: ['Large campus resources', 'Innovation reputation', 'Wide course selection'],
    admissions: ['Academic transcripts', 'Supporting essays if required', 'English proficiency where needed'],
    housing: ['On-campus housing', 'Private apartments', 'Shared student living'],
  },
  {
    slug: 'pace-university',
    name: 'Pace University',
    destination: 'United States',
    destinationSlug: 'usa',
    city: 'New York',
    type: 'Private university',
    tuition: 'USD 32,000 - 52,000 per year',
    livingCosts: 'USD 1,700 - 3,000 per month',
    overview:
      'A U.S. university known for business and professional pathways with strong access to New York career networks.',
    programs: ['Business', 'Finance', 'Computer Science', 'Law', 'Media'],
    scholarships: ['Merit scholarships', 'International student awards', 'Program-based grants'],
    highlights: ['New York location advantage', 'Career-oriented curriculum', 'Professional networking access'],
    admissions: ['Academic transcripts', 'Application essays where needed', 'English test scores for eligible applicants'],
    housing: ['Residence halls', 'Shared New York housing', 'Private student apartments'],
  },
  {
    slug: 'university-of-south-florida',
    name: 'University of South Florida',
    destination: 'United States',
    destinationSlug: 'usa',
    city: 'Tampa',
    type: 'Public research university',
    tuition: 'USD 18,000 - 28,000 per year',
    livingCosts: 'USD 1,200 - 2,100 per month',
    overview:
      'A strong-value U.S. public university with research growth, good campus life, and a warm climate location.',
    programs: ['Public Health', 'Engineering', 'Business', 'Marine Science', 'Computer Science'],
    scholarships: ['International merit awards', 'College-level scholarships', 'Research support routes'],
    highlights: ['Good value for a U.S. public university', 'Growing research reputation', 'Strong health and science options'],
    admissions: ['Academic history', 'Language test scores where required', 'Supporting application materials'],
    housing: ['Campus housing', 'Off-campus apartments', 'Shared student rentals'],
  },
  {
    slug: 'northeastern-university',
    name: 'Northeastern University',
    destination: 'United States',
    destinationSlug: 'usa',
    city: 'Boston',
    type: 'Private research university',
    tuition: 'USD 35,000 - 60,000 per year',
    livingCosts: 'USD 1,800 - 3,000 per month',
    overview:
      'Known for co-op learning, strong employer links, and career-focused academic pathways in the U.S.',
    programs: ['Computer Science', 'Engineering', 'Business', 'Data Science', 'Public Policy'],
    scholarships: ['Merit scholarships', 'International student support', 'Selected graduate funding'],
    highlights: ['Co-op and employability focus', 'Strong Boston ecosystem', 'Highly career-oriented learning'],
    admissions: ['Competitive academics', 'Personal application strength', 'English language readiness'],
    housing: ['Residence halls', 'Boston rentals', 'Private student apartments'],
  },
  {
    slug: 'university-of-auckland',
    name: 'University of Auckland',
    destination: 'New Zealand',
    destinationSlug: 'new-zealand',
    city: 'Auckland',
    type: 'Public research university',
    tuition: 'NZD 28,000 - 42,000 per year',
    livingCosts: 'NZD 1,500 - 2,400 per month',
    overview:
      'New Zealand’s largest university with strong academic reputation, research depth, and broad international recognition.',
    programs: ['Engineering', 'Business', 'Medicine', 'Architecture', 'Data Science'],
    scholarships: ['International student scholarships', 'Faculty awards', 'Graduate research funding'],
    highlights: ['Top New Zealand profile', 'Wide course range', 'Strong city-based opportunities'],
    admissions: ['Academic transcripts', 'English proficiency', 'Supporting program documents where required'],
    housing: ['University accommodation', 'Private city rentals', 'Student apartments'],
  },
  {
    slug: 'massey-university',
    name: 'Massey University',
    destination: 'New Zealand',
    destinationSlug: 'new-zealand',
    city: 'Palmerston North',
    type: 'Public university',
    tuition: 'NZD 24,000 - 37,000 per year',
    livingCosts: 'NZD 1,200 - 2,000 per month',
    overview:
      'A student-friendly university known for flexible learning pathways and strengths in applied and professional fields.',
    programs: ['Agriculture', 'Aviation', 'Business', 'Design', 'Veterinary Science'],
    scholarships: ['International excellence awards', 'Faculty scholarships', 'Graduate support'],
    highlights: ['Applied learning focus', 'Flexible pathways', 'Strong agriculture and design reputation'],
    admissions: ['Academic records', 'English language evidence', 'Supporting documents'],
    housing: ['Campus housing', 'Private shared accommodation', 'Student rentals'],
  },
  {
    slug: 'aut',
    name: 'AUT',
    destination: 'New Zealand',
    destinationSlug: 'new-zealand',
    city: 'Auckland',
    type: 'Public university',
    tuition: 'NZD 25,000 - 39,000 per year',
    livingCosts: 'NZD 1,500 - 2,400 per month',
    overview:
      'A modern New Zealand university recognized for industry alignment, practical learning, and urban campus life.',
    programs: ['Hospitality', 'Business', 'Computer Science', 'Health', 'Communication'],
    scholarships: ['International student scholarships', 'Faculty awards', 'Selected research support'],
    highlights: ['Modern teaching style', 'Industry-facing programs', 'Auckland location'],
    admissions: ['Academic profile', 'Language test scores where applicable', 'Program-level requirements'],
    housing: ['Student residences', 'Private rentals', 'Shared urban housing'],
  },
  {
    slug: 'university-of-otago',
    name: 'University of Otago',
    destination: 'New Zealand',
    destinationSlug: 'new-zealand',
    city: 'Dunedin',
    type: 'Public research university',
    tuition: 'NZD 27,000 - 41,000 per year',
    livingCosts: 'NZD 1,200 - 2,000 per month',
    overview:
      'A respected New Zealand university with strong research depth, a classic student-city feel, and solid health and science programs.',
    programs: ['Medicine', 'Biomedical Sciences', 'Business', 'Law', 'Humanities'],
    scholarships: ['International research scholarships', 'Merit awards', 'Graduate support routes'],
    highlights: ['Strong academic identity', 'Research-led environment', 'Distinctive student culture'],
    admissions: ['Academic records', 'English proficiency', 'Competitive requirements for health programs'],
    housing: ['Residential colleges', 'Private rentals', 'Shared student housing'],
  },
  {
    slug: 'university-of-birmingham-dubai',
    name: 'University of Birmingham Dubai',
    destination: 'Dubai',
    destinationSlug: 'dubai',
    city: 'Dubai',
    type: 'International branch campus',
    tuition: 'AED 60,000 - 130,000 per year',
    livingCosts: 'AED 4,000 - 7,500 per month',
    overview:
      'A Dubai branch campus offering British university standards in a modern regional education hub.',
    programs: ['Business', 'Computer Science', 'Engineering', 'Psychology', 'Education'],
    scholarships: ['Academic scholarships', 'Regional awards', 'Selected tuition discounts'],
    highlights: ['UK degree pathway in Dubai', 'Modern campus setup', 'Strong regional accessibility'],
    admissions: ['Academic qualifications', 'English proficiency evidence', 'Program-specific application materials'],
    housing: ['Private apartments', 'Student residences', 'Shared housing options'],
  },
  {
    slug: 'middlesex-university-dubai',
    name: 'Middlesex Dubai',
    destination: 'Dubai',
    destinationSlug: 'dubai',
    city: 'Dubai',
    type: 'International branch campus',
    tuition: 'AED 40,000 - 75,000 per year',
    livingCosts: 'AED 3,800 - 7,000 per month',
    overview:
      'A popular Dubai campus for students seeking a practical UK-linked education in business, media, and tech-focused fields.',
    programs: ['Business', 'Law', 'Media', 'Computing', 'Psychology'],
    scholarships: ['Academic excellence scholarships', 'Early registration discounts', 'Regional awards'],
    highlights: ['Practical course options', 'Accessible branch campus model', 'Strong student diversity'],
    admissions: ['Academic history', 'Language readiness', 'Supporting study documents'],
    housing: ['Private apartments', 'Student residences', 'Shared accommodation'],
  },
  {
    slug: 'heriot-watt-university-dubai',
    name: 'Heriot-Watt Dubai',
    destination: 'Dubai',
    destinationSlug: 'dubai',
    city: 'Dubai',
    type: 'International branch campus',
    tuition: 'AED 50,000 - 90,000 per year',
    livingCosts: 'AED 4,000 - 7,200 per month',
    overview:
      'A Dubai campus with strong engineering, business, and built environment programs tied to a recognized UK institution.',
    programs: ['Engineering', 'Construction', 'Data Science', 'Business', 'Architecture'],
    scholarships: ['Merit scholarships', 'Tuition discounts', 'Program-specific awards'],
    highlights: ['Engineering and business strength', 'Recognized UK brand', 'Regional employability relevance'],
    admissions: ['Academic transcripts', 'English proficiency', 'Program-specific support documents'],
    housing: ['Student residence options', 'Private apartments', 'Shared city housing'],
  },
  {
    slug: 'murdoch-university-dubai',
    name: 'Murdoch University Dubai',
    destination: 'Dubai',
    destinationSlug: 'dubai',
    city: 'Dubai',
    type: 'International branch campus',
    tuition: 'AED 40,000 - 70,000 per year',
    livingCosts: 'AED 3,800 - 7,000 per month',
    overview:
      'A student-friendly Dubai campus with Australian-linked degrees and accessible international study options.',
    programs: ['Business', 'Cyber Security', 'Psychology', 'Communication', 'Education'],
    scholarships: ['Academic merit support', 'Scholarship discounts', 'Promotional tuition grants'],
    highlights: ['Australian curriculum pathway', 'Practical urban study setup', 'Diverse student cohort'],
    admissions: ['Academic records', 'English language evidence', 'General supporting application documents'],
    housing: ['Private housing', 'Student apartments', 'Shared accommodation'],
  },
  {
    slug: 'eu-business-school',
    name: 'EU Business School',
    destination: 'Europe',
    destinationSlug: 'europe',
    city: 'Barcelona and other campuses',
    type: 'Private business school',
    tuition: 'EUR 12,000 - 25,000 per year',
    livingCosts: 'EUR 900 - 1,700 per month',
    overview:
      'A Europe-focused business school brand with international campuses and business-centered degree options.',
    programs: ['Business Administration', 'International Business', 'Marketing', 'Finance', 'Entrepreneurship'],
    scholarships: ['Merit-based discounts', 'Campus awards', 'Selected tuition support'],
    highlights: ['Business-focused curriculum', 'International campus model', 'Strong urban student settings'],
    admissions: ['Academic history', 'English readiness', 'Interview or motivation materials for some programs'],
    housing: ['Private apartments', 'Shared student housing', 'City residence options'],
  },
  {
    slug: 'university-of-europe-for-applied-sciences',
    name: 'University of Europe',
    destination: 'Europe',
    destinationSlug: 'europe',
    city: 'Germany',
    type: 'Private applied sciences university',
    tuition: 'EUR 10,000 - 18,000 per year',
    livingCosts: 'EUR 850 - 1,500 per month',
    overview:
      'An applied sciences option with international-friendly programs in business, technology, and design fields.',
    programs: ['Business', 'Software Engineering', 'Design', 'Sports Management', 'Psychology'],
    scholarships: ['Merit scholarships', 'International tuition discounts', 'Selected promotional awards'],
    highlights: ['Applied learning style', 'English-taught options', 'Accessible Germany pathway'],
    admissions: ['Academic transcripts', 'English proficiency where needed', 'Program support documents'],
    housing: ['Private rentals', 'Student dormitories', 'Shared housing'],
  },
  {
    slug: 'budapest-metropolitan-university',
    name: 'Budapest Metropolitan University',
    destination: 'Europe',
    destinationSlug: 'europe',
    city: 'Budapest',
    type: 'Private university',
    tuition: 'EUR 5,000 - 10,000 per year',
    livingCosts: 'EUR 700 - 1,200 per month',
    overview:
      'A cost-conscious Europe option for students looking for English-taught programs in a vibrant Central European city.',
    programs: ['Business', 'Communication', 'Tourism', 'Arts and Design', 'International Relations'],
    scholarships: ['Tuition discounts', 'Institutional grants', 'Selected merit awards'],
    highlights: ['Affordable cost profile', 'Strong urban environment', 'Accessible English-taught programs'],
    admissions: ['Academic records', 'Language readiness', 'General application documents'],
    housing: ['Private apartments', 'Shared student flats', 'Residence options'],
  },
  {
    slug: 'constructor-university',
    name: 'Constructor University',
    destination: 'Europe',
    destinationSlug: 'europe',
    city: 'Bremen',
    type: 'Private research-oriented university',
    tuition: 'EUR 20,000 - 30,000 per year',
    livingCosts: 'EUR 850 - 1,400 per month',
    overview:
      'A Germany-based international university with a focused academic community and strong STEM visibility.',
    programs: ['Computer Science', 'Robotics', 'Economics', 'Biochemistry', 'Data Engineering'],
    scholarships: ['Merit-based tuition support', 'Selected need-based support', 'International scholarships'],
    highlights: ['Strong STEM orientation', 'International student culture', 'Compact campus environment'],
    admissions: ['Academic strength', 'English proficiency', 'Supporting application materials'],
    housing: ['Campus housing', 'Private local rentals', 'Student accommodation'],
  },
  {
    slug: 'taylors-university',
    name: "Taylor's University",
    destination: 'Malaysia',
    destinationSlug: 'malaysia',
    city: 'Kuala Lumpur',
    type: 'Private university',
    tuition: 'USD 7,000 - 15,000 per year',
    livingCosts: 'USD 450 - 950 per month',
    overview:
      'A well-known Malaysia institution with strong hospitality, business, and health-related programs.',
    programs: ['Hospitality', 'Business', 'Medicine', 'Architecture', 'Computer Science'],
    scholarships: ['Merit scholarships', 'Partial tuition grants', 'Faculty awards'],
    highlights: ['Strong private university brand', 'Urban campus experience', 'Good affordability balance'],
    admissions: ['Academic transcripts', 'English readiness', 'General application materials'],
    housing: ['Residence halls', 'Private apartments', 'Shared housing'],
  },
  {
    slug: 'sunway-university',
    name: 'Sunway University',
    destination: 'Malaysia',
    destinationSlug: 'malaysia',
    city: 'Kuala Lumpur',
    type: 'Private university',
    tuition: 'USD 6,000 - 14,000 per year',
    livingCosts: 'USD 450 - 900 per month',
    overview:
      'A student-friendly Malaysia option with modern facilities, industry-oriented teaching, and strong campus life.',
    programs: ['Business', 'Accounting', 'IT', 'Communication', 'Hospitality'],
    scholarships: ['Merit awards', 'International student scholarships', 'School-level discounts'],
    highlights: ['Modern campus', 'Affordable urban study path', 'Applied curriculum'],
    admissions: ['Academic records', 'English evidence where needed', 'Application support documents'],
    housing: ['Student residences', 'Private rentals', 'Shared apartments'],
  },
  {
    slug: 'ucsi-university',
    name: 'UCSI University',
    destination: 'Malaysia',
    destinationSlug: 'malaysia',
    city: 'Kuala Lumpur',
    type: 'Private university',
    tuition: 'USD 5,000 - 13,000 per year',
    livingCosts: 'USD 450 - 900 per month',
    overview:
      'A cost-effective Malaysian university with broad international enrolment and practical program choices.',
    programs: ['Medicine', 'Engineering', 'Business', 'Music', 'Pharmacy'],
    scholarships: ['Academic excellence awards', 'International tuition support', 'Selected grants'],
    highlights: ['Broad field options', 'Accessible price point', 'Strong private sector ties'],
    admissions: ['Academic profile', 'Language readiness', 'Supporting application documents'],
    housing: ['On-campus options', 'Private student housing', 'Shared rentals'],
  },
  {
    slug: 'monash-university-malaysia',
    name: 'Monash University Malaysia',
    destination: 'Malaysia',
    destinationSlug: 'malaysia',
    city: 'Kuala Lumpur',
    type: 'International branch campus',
    tuition: 'USD 9,000 - 20,000 per year',
    livingCosts: 'USD 500 - 1,000 per month',
    overview:
      'A branch campus offering Monash-linked degrees at a lower overall cost than many Western destinations.',
    programs: ['Medicine', 'Business', 'Engineering', 'Computer Science', 'Psychology'],
    scholarships: ['Merit scholarships', 'Campus awards', 'Faculty support'],
    highlights: ['Recognized Australian-linked degree', 'Cost-effective branch campus model', 'Strong academics'],
    admissions: ['Academic transcripts', 'English language readiness', 'General supporting documents'],
    housing: ['Student residences', 'Private apartments', 'Shared housing'],
  },
  {
    slug: 'bahcesehir-university',
    name: 'Bahcesehir University',
    destination: 'Turkey',
    destinationSlug: 'turkey',
    city: 'Istanbul',
    type: 'Private university',
    tuition: 'USD 8,000 - 20,000 per year',
    livingCosts: 'USD 500 - 1,100 per month',
    overview:
      'A private Istanbul university known for international orientation, city access, and modern program offerings.',
    programs: ['Engineering', 'Architecture', 'Business', 'Medicine', 'Communication'],
    scholarships: ['Merit scholarships', 'International tuition discounts', 'Selected program awards'],
    highlights: ['Istanbul location', 'Modern campus environment', 'Good international student appeal'],
    admissions: ['Academic records', 'Language readiness depending on program', 'Supporting application materials'],
    housing: ['Private rentals', 'Student dorms', 'Shared city housing'],
  },
  {
    slug: 'istanbul-aydin-university',
    name: 'Istanbul Aydin University',
    destination: 'Turkey',
    destinationSlug: 'turkey',
    city: 'Istanbul',
    type: 'Private university',
    tuition: 'USD 6,000 - 16,000 per year',
    livingCosts: 'USD 500 - 1,100 per month',
    overview:
      'A practical Turkey study option with broad program choice and an accessible cost profile in Istanbul.',
    programs: ['Business', 'Engineering', 'Aviation', 'Health Sciences', 'Media'],
    scholarships: ['Merit discounts', 'International student support', 'Program-specific awards'],
    highlights: ['Accessible cost structure', 'Wide subject range', 'Istanbul-based student life'],
    admissions: ['Academic qualifications', 'Program language requirements', 'Supporting documents'],
    housing: ['Dormitories', 'Private apartments', 'Shared housing'],
  },
  {
    slug: 'ozyegin-university',
    name: 'Ozyegin University',
    destination: 'Turkey',
    destinationSlug: 'turkey',
    city: 'Istanbul',
    type: 'Private university',
    tuition: 'USD 9,000 - 22,000 per year',
    livingCosts: 'USD 550 - 1,150 per month',
    overview:
      'A modern Istanbul university with a strong reputation in entrepreneurship, engineering, and business-oriented learning.',
    programs: ['Business', 'Engineering', 'Architecture', 'Law', 'Computer Science'],
    scholarships: ['Merit scholarships', 'Tuition reductions', 'Faculty awards'],
    highlights: ['Modern campus', 'Entrepreneurial emphasis', 'Strong English-medium options'],
    admissions: ['Academic records', 'Language requirements', 'Supporting documents for selected programs'],
    housing: ['Campus housing', 'Private rentals', 'Shared accommodation'],
  },
  {
    slug: 'istanbul-medipol-university',
    name: 'Istanbul Medipol University',
    destination: 'Turkey',
    destinationSlug: 'turkey',
    city: 'Istanbul',
    type: 'Private university',
    tuition: 'USD 7,000 - 20,000 per year',
    livingCosts: 'USD 500 - 1,100 per month',
    overview:
      'A growing university known especially for health-related and professional degree pathways in Istanbul.',
    programs: ['Medicine', 'Dentistry', 'Pharmacy', 'Engineering', 'Business'],
    scholarships: ['Academic merit support', 'International student discounts', 'Health faculty awards'],
    highlights: ['Strong health sciences visibility', 'Urban campus opportunity', 'International student access'],
    admissions: ['Academic transcripts', 'Program-specific requirements', 'Language and identity documents'],
    housing: ['Dormitories', 'Private rentals', 'Shared student housing'],
  },
  {
    slug: 'tsinghua-university',
    name: 'Tsinghua University',
    destination: 'China',
    destinationSlug: 'china',
    city: 'Beijing',
    type: 'Public research university',
    tuition: 'USD 4,500 - 11,000 per year',
    livingCosts: 'USD 650 - 1,200 per month',
    overview:
      'One of China’s most recognized universities, especially strong in engineering, technology, and research-led innovation.',
    programs: ['Engineering', 'Artificial Intelligence', 'Architecture', 'Business', 'Public Policy'],
    scholarships: ['Chinese Government Scholarship', 'University scholarships', 'Research funding routes'],
    highlights: ['Top-tier global reputation', 'Strong STEM ecosystem', 'Excellent research infrastructure'],
    admissions: ['Competitive academic profile', 'Program language readiness', 'Strong supporting application materials'],
    housing: ['Campus housing', 'Student dormitories', 'Private city accommodation'],
  },
  {
    slug: 'peking-university',
    name: 'Peking University',
    destination: 'China',
    destinationSlug: 'china',
    city: 'Beijing',
    type: 'Public research university',
    tuition: 'USD 4,500 - 10,500 per year',
    livingCosts: 'USD 650 - 1,200 per month',
    overview:
      'A globally respected Chinese university with particular strength in humanities, business, research, and social sciences.',
    programs: ['Economics', 'International Relations', 'Business', 'Medicine', 'Computer Science'],
    scholarships: ['Chinese Government Scholarship', 'University merit awards', 'Graduate research support'],
    highlights: ['Prestige global profile', 'Strong interdisciplinary ecosystem', 'High scholarship visibility'],
    admissions: ['Strong academics', 'Program-specific language readiness', 'Well-prepared supporting documents'],
    housing: ['Dormitories', 'Campus housing', 'Private Beijing rentals'],
  },
  {
    slug: 'fudan-university',
    name: 'Fudan University',
    destination: 'China',
    destinationSlug: 'china',
    city: 'Shanghai',
    type: 'Public research university',
    tuition: 'USD 4,000 - 10,000 per year',
    livingCosts: 'USD 700 - 1,250 per month',
    overview:
      'A major Shanghai university with strong medicine, business, and international academic visibility.',
    programs: ['Medicine', 'Business', 'Journalism', 'Public Health', 'Data Science'],
    scholarships: ['Government scholarships', 'Fudan scholarships', 'Graduate and research funding'],
    highlights: ['Shanghai location', 'Research strength', 'Broad international student access'],
    admissions: ['Academic records', 'Language readiness', 'Competitive supporting materials'],
    housing: ['University dorms', 'Private apartments', 'Shared housing'],
  },
  {
    slug: 'shanghai-jiao-tong-university',
    name: 'Shanghai Jiao Tong University',
    destination: 'China',
    destinationSlug: 'china',
    city: 'Shanghai',
    type: 'Public research university',
    tuition: 'USD 4,500 - 11,000 per year',
    livingCosts: 'USD 700 - 1,250 per month',
    overview:
      'A high-performing Chinese university known for engineering, technology, business, and deep research capability.',
    programs: ['Engineering', 'Computer Science', 'Business', 'Biomedicine', 'Materials Science'],
    scholarships: ['Chinese Government Scholarship', 'University scholarships', 'Research fellowships'],
    highlights: ['Strong global ranking presence', 'Technology and research reputation', 'Shanghai city advantage'],
    admissions: ['Strong grades', 'Language or program readiness', 'Clear academic fit and supporting documents'],
    housing: ['Campus housing', 'Dormitories', 'Private rentals in Shanghai'],
  },
]

const UNIVERSITY_BY_SLUG = new Map(UNIVERSITY_CATALOG.map((item) => [item.slug, item]))
const UNIVERSITY_BY_NAME = new Map(UNIVERSITY_CATALOG.map((item) => [item.name, item]))

export function getUniversityBySlug(slug) {
  return UNIVERSITY_BY_SLUG.get(slug) || null
}

export function getUniversityByName(name) {
  return UNIVERSITY_BY_NAME.get(name) || null
}

export function buildUniversityDetailPath(slug) {
  return `/universities/${slug}`
}
