import { university_of_toronto } from './university-of-toronto.js'
import { university_of_british_columbia } from './university-of-british-columbia.js'
import { mcgill_university } from './mcgill-university.js'
import { university_of_manitoba } from './university-of-manitoba.js'
import { university_of_alberta } from './university-of-alberta.js'
import { york_university } from './york-university.js'
import { university_of_waterloo } from './university-of-waterloo.js'
import { university_of_ottawa } from './university-of-ottawa.js'
import { university_of_calgary } from './university-of-calgary.js'
import { simon_fraser_university } from './simon-fraser-university.js'
import { university_of_saskatchewan } from './university-of-saskatchewan.js'
import { university_of_guelph } from './university-of-guelph.js'
import { carleton_university } from './carleton-university.js'
import { university_of_victoria } from './university-of-victoria.js'
import { dalhousie_university } from './dalhousie-university.js'
import { university_of_windsor } from './university-of-windsor.js'
import { university_of_regina } from './university-of-regina.js'
import { university_of_northern_british_columbia } from './university-of-northern-british-columbia.js'
import { university_of_lethbridge } from './university-of-lethbridge.js'
import { university_of_prince_edward_island } from './university-of-prince-edward-island.js'

export const canadaUniversities = [university_of_toronto, university_of_british_columbia, mcgill_university, university_of_manitoba, university_of_alberta, york_university, university_of_waterloo, university_of_ottawa, university_of_calgary, simon_fraser_university, university_of_saskatchewan, university_of_guelph, carleton_university, university_of_victoria, dalhousie_university, university_of_windsor, university_of_regina, university_of_northern_british_columbia, university_of_lethbridge, university_of_prince_edward_island]
