import { university_of_melbourne } from './university-of-melbourne.js'
import { university_of_sydney } from './university-of-sydney.js'
import { university_of_new_south_wales_unsw } from './university-of-new-south-wales-unsw.js'
import { australian_national_university_anu } from './australian-national-university-anu.js'
import { monash_university } from './monash-university.js'
import { university_of_queensland } from './university-of-queensland.js'
import { university_of_western_australia } from './university-of-western-australia.js'
import { university_of_adelaide } from './university-of-adelaide.js'
import { university_of_technology_sydney } from './university-of-technology-sydney.js'
import { queensland_university_of_technology } from './queensland-university-of-technology.js'
import { rmit_university } from './rmit-university.js'
import { deakin_university } from './deakin-university.js'
import { university_of_wollongong } from './university-of-wollongong.js'
import { curtin_university } from './curtin-university.js'
import { university_of_newcastle } from './university-of-newcastle.js'
import { macquarie_university } from './macquarie-university.js'
import { griffith_university } from './griffith-university.js'
import { la_trobe_university } from './la-trobe-university.js'
import { university_of_south_australia } from './university-of-south-australia.js'
import { university_of_tasmania } from './university-of-tasmania.js'

export const australiaUniversities = [university_of_melbourne, university_of_sydney, university_of_new_south_wales_unsw, australian_national_university_anu, monash_university, university_of_queensland, university_of_western_australia, university_of_adelaide, university_of_technology_sydney, queensland_university_of_technology, rmit_university, deakin_university, university_of_wollongong, curtin_university, university_of_newcastle, macquarie_university, griffith_university, la_trobe_university, university_of_south_australia, university_of_tasmania]
